services:
  beermapping:
    image: vilee/beermapping:latest
    container_name: bm
    ports:
      - "8080:8080"

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_API_VERSION=1.40
    command: --interval 30 bm
